version: '3.9'

services:
  backend:
    container_name: image-processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
