version: '3.9'

services:
  backend:
    container_name: image-processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/ubuntu/.u2net:/root/.u2net   # ✅ punto clave
    restart: unless-stopped
